---
name: Release
on:
  pull_request:

permissions:
  contents: write
  pull-requests: read

jobs:
  commitlint_and_release:
    name: Commit lint and release
    uses: nrkno/github-workflow-semantic-release/.github/workflows/workflow.yaml@v5.0.2
    secrets: inherit
    with:
        lint-enabled: 'false'